spring:
  application:
    name: bootlogging
  profiles:
    active: local
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev 

logging:
    file:
        name: /users/hyoungdonju/logs/${spring.application.name}.log
    logback.rollingpolicy:
        max-file-size: 1MB
        max-history: 5